server:
  port: '8080'

dffrnt:
  auth:
    jwt:
      secret: 'top secret'

core:
  server:
    cors:
      allowed.origins: 'http://localhost:4200 '
      allowed.methods: 'GET, POST, PUT, DELETE, OPTIONS'
      allowed.headers: 'Authorization, RefreshToken, Content-Type'
      exposed.headers: 'Authorization, RefreshToken'